### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by y2keeth** [bj-rn/texconvgui#1]
have a way to add newer texconv  formats

**Comment by bj-rn** [comment]
Hello, which formats are you refering to, [DXGI](https://github.com/microsoft/DirectXTex/blob/70909fd6be3d7fc0112910daaeb4e0ab1dcce587/Texconv/texconv.cpp#L234)?

**Comment by y2keeth** [comment]
> Hello, which formats are you refering to, [DXGI](https://github.com/microsoft/DirectXTex/blob/70909fd6be3d7fc0112910daaeb4e0ab1dcce587/Texconv/texconv.cpp#L234)?

the newest version of texconv now supports dtx 5 rxgb because of me lol
https://github.com/microsoft/DirectXTex/releases/tag/jun2023

**Comment by bj-rn** [comment]
https://github.com/bj-rn/texconvgui/releases/tag/2.0.0

**Comment by y2keeth** [comment]
great thanks
