### ISSUE TITLE
Not an issue, but help on how to exactly use this

### ISSUE THREAD

**Issue by evil-trainer** [bj-rn/texconvgui#2]
Hi, I've been trying to understand how to use texconv to convert from tex to dds and vice-versa (don't even know if this is possible at all). Sorry if this sounds like a dumb question, but I'm a beginner and need help with this, if possible!

**Comment by bj-rn** [comment]
Hello, afaik Tex is a proprietary Nintendo format and it's not supported by [Texconv](https://github.com/Microsoft/DirectXTex/wiki/Texconv).
Maybe check out [BrawlCrate](https://github.com/soopercool101/BrawlCrate).

**Comment by evil-trainer** [comment]
Thanks for your reply!

Oh, and I forgot to mention it was actually from Capcom's MT Framework. Sorry!
But yeah, it's from a Switch game and I did manage to use Texconv GUI to export a while ago, to batch convert from tex to dds. It was a BC7 lot, if I'm not mistaken.

Also, I have a tool (a .bat file, actually) that uses Texconv to convert from dds to this tex format, but not the other way around. I was hoping TexConvGui could help me to automate the batch conversion of tex to dds.

But thanks for the clarification!

**Comment by bj-rn** [comment]
Can you share some test tex textures and that bat file? Can't promise anything but will take a look.

**Comment by evil-trainer** [comment]
> Can you share some test tex textures and that bat file? Can't promise anything but will take a look.

Sure! Thank you very much for helping!

Test textures:
https://www.mediafire.com/file/28ivcuxac1p8arp/RE5_TEX.7z/file

.Bat file with the tools I use to convert from dds to tex:
https://www.mediafire.com/file/k8wvyqgzrbrn13k/convert_textures.bat/file

The workflow I use is the following:

1- Since I don't have a tool to convert from tex to dds, I bruteforce my way in with Rawtex. For this, I must open a hexadecimal editor, and find the **offset of the beginning** of the image, discover the compression format used and the size of the  image. Then Rawtex will give me a dds file.

2- With the dds extracted by Rawtex, I start editing it.

3- When I'm done, I place my edit in the 'dds' folder of the tool I sent to you.

4- Now, I place the vanilla tex which I used in Rawtex to give me the dds, in the 'original_tex' folder of the tool I sent to you.

5- Next step is make sure my 'convert_textures.bat' file has the decimal value  of the offset of the dds image I got on step 1.

6- Now I only have to run the bat and it'll generate the working edited tex, inside the 'new_tex' folder of the toolset I sent you.

7- And that's it. Now I have to repeat the step 1 hundreds of times for every texture I have to edit because I don't have a batch conversion tool 😩

Here's hoping you can figure this out 😁

**Comment by bj-rn** [comment]
Ok this is defnitely outside the scope of this tool. But I found [this post](https://www.vg-resource.com/thread-34368-post-648874.html#pid648874) and tried the attached [MegaMan11Switch_TEX script](https://mega.nz/#!GtgXyCjC!UxekZ7h5X1iJnlWWLraeabi5I50Uhwq1J4Cg-sEWiQg) with [QuickBMS](https://aluigi.altervista.org/quickbms.htm) and your test textures and it works.

**Comment by evil-trainer** [comment]
> Ok this is defnitely outside the scope of this tool. But I found [this post](https://www.vg-resource.com/thread-34368-post-648874.html#pid648874) and tried the attached [MegaMan11Switch_TEX script](https://mega.nz/#!GtgXyCjC!UxekZ7h5X1iJnlWWLraeabi5I50Uhwq1J4Cg-sEWiQg) with [QuickBMS](https://aluigi.altervista.org/quickbms.htm) and your test textures and it works. 
> 

Oh, that's weird. I already checked that and it didn't work for the textures from RE0, which used the same engine, same .tex files and even has the same offset values for image extraction and it didn't work. I'll try this again. Thanks!

**Comment by evil-trainer** [comment]
MAN, IT WORKED! I can't believe I had this script with me for MONTHS and I was struggling to parse every freaking .tex one by one by hand lol
With quickbms, I'll finally be able to batch convert those hundreds of .tex to .dds all at once! I only wish quickbms could generate a .txt with the image type compression used in the .tex, so I could use to convert back from .dds to .tex. But that's ok, that's a minor inconvenience that I can live with.

Thank you, for your help!
